ALTER TABLE members
ADD COLUMN level INTEGER unsigned NOT NULL default 1 AFTER highscore,
ADD COLUMN ach001 TINYINT NOT NULL default 0 AFTER level,
ADD COLUMN ach002 TINYINT NOT NULL default 0 AFTER ach001,
ADD COLUMN ach003 TINYINT NOT NULL default 0 AFTER ach002,
ADD COLUMN sound TINYINT NOT NULL default 1 AFTER ach003,
ADD COLUMN tutorial TINYINT NOT NULL default 1 AFTER sound